---
galaxy_info:
  author: Emmanuel Okose
  description: "Ansible role to install and configure WordPress with EFS mounting and RDS database"
  license: MIT
  min_ansible_version: "2.9"
  platforms:
  - name: EL
    versions:
      - 7
      - 8
    dependencies: []

  dependencies: []