---
- name: Install Nginx (RedHat-based)
  ansible.builtin.yum:
    name: "{{ nginx_package }}"
    state: present
  when: ansible_os_family == "RedHat"
  become: yes

- name: Install Nginx (Debian-based)
  ansible.builtin.apt:
    name: "{{ nginx_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: yes

- name: Ensure Nginx service is started and enabled
  ansible.builtin.service:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
  become: yes